# AutheticationService/.github/workflows/ci.yml
name: CI - Auth Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Backend/AuthenticationService/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Backend/AuthenticationService/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd AuthenticationService
          npm install

      - name: Run Linter
        run: |
          cd AuthenticationService
          npm run lint

      - name: Run Tests
        run: |
          cd AuthenticationService
          npm test
