# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Leads_Workflow CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Backend/LeadsService/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Backend/LeadsService/**'

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: 'Backend/LeadsService/package-lock.json' # חשוב מאוד!

    - name: Install dependencies
      working-directory: Backend/LeadsService
      run: npm install
           npm install --save-dev jest

    - name: Run tests
      working-directory: Backend/LeadsService
      run: npm run test
    - name: npm run linter
      working-directory: Backend/LeadsService
      run: npm run lint
  # deploy-server:
  #     needs: build-and-test
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: activate deploy hook
  #         run: |
            
    
